# Autogenerated wrapper script for primecount_jll for aarch64-apple-darwin-march+apple_m1
export libprimecount, libprimesieve, primecount

using LLVMOpenMP_jll
JLLWrappers.@generate_wrapper_header("primecount")
JLLWrappers.@declare_library_product(libprimecount, "@rpath/libprimecount.7.dylib")
JLLWrappers.@declare_library_product(libprimesieve, "@rpath/libprimesieve.9.dylib")
JLLWrappers.@declare_executable_product(primecount)
function __init__()
    JLLWrappers.@generate_init_header(LLVMOpenMP_jll)
    JLLWrappers.@init_library_product(
        libprimecount,
        "lib/libprimecount.7.2.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libprimesieve,
        "lib/libprimesieve.9.7.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        primecount,
        "bin/primecount",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
